/*
 * InterfazAcceso.java
 *
 * Created on 15-mar-2013, 16:22:20
 */
package InterfazUsuario;

import GestionDeUsuarios.*;
import ServiciosAlmacenamiento.BaseDatos;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Interfaz de acceso
 *
 * @author Compu-global-Hiper-mega-Net
 *
 * /*
 ******************************************************************************
 * (c) Copyright 2013
 *
 * Moisés Gautier Gómez Julio Ros Martínez Francisco Javier Gómez del Olmo
 * Francisco Santolalla Quiñonero Carlos Jesús Fernández Basso Alexander Moreno
 * Borrego Jesús Manuel Contreras Siles Diego Muñoz Rio
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 * *****************************************************************************
 */
/**
 * Clase inicial de la aplicación
 *
 * @author Compu-global-Hiper-mega-Net
 */
public class Acceso extends javax.swing.JFrame {
    /**
     * Constructor de la clase de acceso a la aplicación.
     */
    public Acceso() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        userTextfield = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        authenticateButton = new javax.swing.JButton();
        passTextfield = new javax.swing.JPasswordField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de acceso");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        titulo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo1.setText("Basketball Management");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(titulo1, gridBagConstraints);

        titulo2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo2.setText("Application");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel1.add(titulo2, gridBagConstraints);

        userTextfield.setColumns(20);
        userTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userTextfieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(userTextfield, gridBagConstraints);

        userLabel.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 5);
        jPanel1.add(userLabel, gridBagConstraints);

        passLabel.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 41, 10, 5);
        jPanel1.add(passLabel, gridBagConstraints);

        authenticateButton.setText("Entrar");
        authenticateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticateButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(authenticateButton, gridBagConstraints);

        passTextfield.setColumns(20);
        passTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passTextfieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(passTextfield, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void authenticateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticateButtonActionPerformed
    BaseDatos accesoBD = new BaseDatos();

    String usuario = userTextfield.getText();
    String pass = String.valueOf(passTextfield.getPassword());
    String consulta_acceso = "SELECT * FROM usuario "
            + "WHERE user='" + usuario + "' AND clave='" + pass + "'";

    ResultSet retSet = GestorUsuarios.consultarUsuario(accesoBD, consulta_acceso);
    try {
        if (retSet.next()) {
            (new PantallaPrincipal(accesoBD, usuario)).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Usuario o contraseña incorrectos", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException ex) {
        System.out.print(ex.getMessage());
    }
}//GEN-LAST:event_authenticateButtonActionPerformed

    private void userTextfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextfieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BaseDatos accesoBD = new BaseDatos();
            
            String usuario = userTextfield.getText();
            String pass = String.valueOf(passTextfield.getPassword());
            String consulta_acceso = "SELECT * FROM usuario "
                    + "WHERE user='" + usuario + "' AND clave='" + pass + "'";
            
            ResultSet retSet = GestorUsuarios.consultarUsuario(accesoBD, consulta_acceso);
            try {
                if (retSet.next()) {
                    (new PantallaPrincipal(accesoBD, usuario)).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Usuario o contraseña incorrectos", "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                System.out.print(ex.getMessage());
            }
        }
    }//GEN-LAST:event_userTextfieldKeyReleased

    private void passTextfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTextfieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BaseDatos accesoBD = new BaseDatos();
            
            String usuario = userTextfield.getText();
            String pass = String.valueOf(passTextfield.getPassword());
            String consulta_acceso = "SELECT * FROM usuario "
                    + "WHERE user='" + usuario + "' AND clave='" + pass + "'";
            
            ResultSet retSet = GestorUsuarios.consultarUsuario(accesoBD, consulta_acceso);
            try {
                if (retSet.next()) {
                    (new PantallaPrincipal(accesoBD, usuario)).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Usuario o contraseña incorrectos", "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                System.out.print(ex.getMessage());
            }
        }
    }//GEN-LAST:event_passTextfieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authenticateButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passTextfield;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextfield;
    // End of variables declaration//GEN-END:variables
}