/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

import GestionDeAlumnos.*;
import ServiciosAlmacenamiento.BaseDatos;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 ******************************************************************************
 (c) Copyright 2013 
 * 
 * Moisés Gautier Gómez
 * Julio Ros Martínez
 * Francisco Javier Gómez del Olmo
 * Francisco Santolalla Quiñonero
 * Carlos Jesús Fernández Basso
 * Alexander Moreno Borrego
 * Jesús Manuel Contreras Siles
 * Diego Muñoz Rio
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************
 */
/**
 * Formulario que añade un alumno a la base de datos
 * Clase para añadir y quitar alumnos a una actividad
 * @author Jesus Manuel Contreras Siles
 * @version 1.0
 */
public class AñadirAlumno extends javax.swing.JFrame {

    int idTemporada, idActividad;
    BaseDatos accesoBD;
    List<Integer> listaIDAlumnos = new ArrayList<>();
    List<Integer> listaIDAlumnosQuitados = new ArrayList<>();
    int sizeModelo;

    /**
     * Metodo constructor por defecto.
     */
    public AñadirAlumno() {
        initComponents();
    }
		
		/**
		 * Constructor de la clase.
		 * @param acceso BaseDatos (BaseDatos) con el acceso a la base de datos.
		 * @param idTemp int (entero) con el identificador de la temporada.
		 * @param idAct int (entero) con el identificador de la actividad a la que se van a añadir alumnos.
		 */

    public AñadirAlumno(BaseDatos acceso, int idTemp, int idAct) {
        accesoBD = acceso;
        initComponents();
        idTemporada = idTemp;
        idActividad = idAct;
        MostrarAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Buscar = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        NombreTextField = new javax.swing.JTextField();
        PrimerApellido = new javax.swing.JLabel();
        PrimerApellidoTextField = new javax.swing.JTextField();
        SegundoApellido = new javax.swing.JLabel();
        SegundoApellidoTextField = new javax.swing.JTextField();
        Añadir = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AlumnosSelecionados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaAlumnos = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlumnosMostrados = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        AlumnosMostradosLabel = new javax.swing.JLabel();
        Quitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titulo.setText("Añadir alumno");

        Buscar.setText("Buscar por");

        Nombre.setText("Nombre");

        NombreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NombreTextFieldKeyReleased(evt);
            }
        });

        PrimerApellido.setText("Primer Apellido");

        PrimerApellidoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PrimerApellidoTextFieldKeyReleased(evt);
            }
        });

        SegundoApellido.setText("Segudno Apellido");

        SegundoApellidoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SegundoApellidoTextFieldKeyReleased(evt);
            }
        });

        Añadir.setText("Añadir");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Alumnos Seleccionados");

        AlumnosSelecionados.setText("0");

        ListaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListaAlumnos);

        AlumnosMostrados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(AlumnosMostrados);

        jLabel2.setText("Alumnos Apuntados:");

        AlumnosMostradosLabel.setText("0");

        Quitar.setText("Quitar");
        Quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrimerApellido)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Salir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(PrimerApellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SegundoApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SegundoApellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buscar)
                            .addComponent(Titulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quitar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Añadir, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AlumnosSelecionados)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlumnosMostradosLabel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Titulo)
                .addGap(29, 29, 29)
                .addComponent(Buscar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(NombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimerApellido)
                    .addComponent(PrimerApellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SegundoApellido)
                    .addComponent(SegundoApellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(AlumnosMostradosLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(AlumnosSelecionados)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Añadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Quitar)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(Guardar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


		/** 
		 * Metodo constructor, activado por el boton "Añadir" para añardir alumnos.
		 * @param evt (java.awt.event.ActionEvent) con el evento.
		 */

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed

        List<String> listaAlumnos = new ArrayList<>();
        listaAlumnos.addAll(ListaAlumnos.getSelectedValuesList());
        DefaultListModel modelo = new DefaultListModel();
        DefaultListModel model = new DefaultListModel();
        modelo = (DefaultListModel) AlumnosMostrados.getModel();
        sizeModelo = modelo.size();
        for (int i = 0; i < listaAlumnos.size(); i++) {
            modelo.addElement(listaAlumnos.get(i));
        }
        AlumnosMostrados.setModel(modelo);

        ActualizarJlist();


    }//GEN-LAST:event_AñadirActionPerformed

		/**
		 * Metodo constructor, activado por el boton "Salir" que cierra el frame.
	   * @param evt (java.awt.event.ActionEvent) con el evento.
		 */

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {                                      

        this.setVisible(false);
    }

		/**
		 * Metodo consultor que genera una consulta para listar los alumnos disponibles.
		 * @return String (cadena) con el atributo interno de la consulta.
		 */

    private String leerConsulta() {
        String consulta = new String("SELECT nombre, primerApellido, segundoApellido from alumno ");
        String condicion = new String("WHERE ");

        if (!NombreTextField.getText().equals("") || !PrimerApellidoTextField.getText().equals("")
                || !SegundoApellidoTextField.getText().equals("")) {
            if (!NombreTextField.getText().equals("")) {
                condicion = condicion + " nombre = '" + NombreTextField.getText() + "' AND";
            }
            if (!PrimerApellidoTextField.getText().equals("")) {
                condicion = condicion + " primerApellido = '" + PrimerApellidoTextField.getText() + "' AND";
            }
            if (!SegundoApellidoTextField.getText().equals("")) {
                condicion = condicion + " segundoApellido = '" + SegundoApellidoTextField.getText() + "' AND";
            }

        }

        condicion = condicion + " idAlumno NOT IN (select Alumno_idAlumno from pagoactividades WHERE Actividades_idActividades = "
                + idActividad + ")";
        consulta = consulta + condicion;
        System.out.print("\n\n Consulta todos alumnos" + consulta);
        return consulta;
    }

		/**
		 * Metodo consultor para mostrar los alumnos introducidos en la actividad.
		 */

    private void alumnosSelecionados() {

        String consulta = ("SELECT nombre, primerApellido, segundoApellido from alumno WHERE idAlumno IN "
                + "(select Alumno_idAlumno from pagoactividades where Actividades_idActividades =" + idActividad + ")");

        ResultSet retset;
        int nAl = 0;

        retset = accesoBD.ejecutaConsulta(consulta);

        DefaultListModel modelo = new DefaultListModel();
        try {
            while (retset.next()) {
                modelo.addElement(retset.getString("primerApellido")
                        + " " + retset.getString("segundoApellido") + " " + retset.getString("nombre"));
                nAl++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AñadirAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        AlumnosMostrados.setModel(modelo);
        AlumnosMostradosLabel.setText(Integer.toString(nAl));

    }
		
		/**
		 * Metodo consultor que muestra los alumnos disponibles para la actividad.
		 */


    private void MostrarAlumnos() {

        ListaAlumnos.removeAll();
        AlumnosMostrados.removeAll();
        try {
            String mostrar_alumnos = leerConsulta();
            ResultSet retset;
            retset = accesoBD.ejecutaConsulta(mostrar_alumnos);
            DefaultListModel modelo = new DefaultListModel();
            while (retset.next()) {
                modelo.addElement(retset.getString("primerApellido")
                        + " " + retset.getString("segundoApellido") + " " + retset.getString("nombre"));
            }
            ListaAlumnos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(AñadirAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }

        alumnosSelecionados();
    }

		/**
		 * Metodo constructor, activdado por el boton (Guardar) que guarda los cambios realizados.
		 * @param evt (java.awt.event.ActionEvent) con el evento.
		 */

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {

        DefaultListModel modelo = new DefaultListModel();
        List<String> listaAlumnos = new ArrayList<>();

        modelo = (DefaultListModel) AlumnosMostrados.getModel();
        for (int i = 0; i < modelo.size(); i++) {
            listaAlumnos.add((String) modelo.get(i));
        }


        System.out.print("\n Antes del try" + listaAlumnos);
        try {
            System.out.print("\n En el try" + listaAlumnos);
            listaIDAlumnos = GestorAlumnos.getIdAl(accesoBD, listaAlumnos);
        } catch (SQLException ex) {
            Logger.getLogger(AñadirAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (listaIDAlumnos.size() > 0) {
            ResultSet retset, rts;
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

            for (int i = 0; i < listaIDAlumnos.size(); i++) {
                try {
                    GestionActividades.GestorActividad.InsertarAlumnoActividad(accesoBD, listaIDAlumnos.get(i), idTemporada, idActividad);
                } catch (SQLException ex) {
                    Logger.getLogger(AñadirAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            JOptionPane.showMessageDialog(null, "Datos guardados",
                    "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "No has seleccionado alumnos",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }



    }

		/**
		 * Metodo constructor, activado por el boton "Quitar" para quitar alumnos introducidos en la actividad.
		 * @param evt (java.awt.event.ActionEvent) con el evento.
		 */

    private void QuitarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        List<String> listaAlumnosQuitados = new ArrayList<>();
        listaAlumnosQuitados.addAll(AlumnosMostrados.getSelectedValuesList());
        int[] indices = AlumnosMostrados.getSelectedIndices();
        DefaultListModel modelo = new DefaultListModel();
        DefaultListModel modeloAlumnos = new DefaultListModel();

        modeloAlumnos = (DefaultListModel) ListaAlumnos.getModel();
        modelo = (DefaultListModel) AlumnosMostrados.getModel();
        try {
            listaIDAlumnosQuitados = GestorAlumnos.getIdAl(accesoBD, listaAlumnosQuitados);
            System.out.printf("\nID alumnos actividades", listaIDAlumnosQuitados);
            GestionActividades.GestorActividad.eliminaraAlumnos(accesoBD, listaIDAlumnosQuitados, idActividad);
        } catch (SQLException ex) {
            Logger.getLogger(AñadirAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        for (int i = 0; i < indices.length; i++) {
            modeloAlumnos.addElement(modelo.get(indices[i]));
            modelo.remove(indices[i]);
        }


        AlumnosMostrados.setModel(modelo);
        ListaAlumnos.setModel(modeloAlumnos);

    }

		/**
		 * Metodo consultor, activado cuando se introduce caracteres en el campo "Nombre", para buscar alumnos por nombre.
		 * @param evt (java.awt.event.KeyEvent) con el evento.
		 */

    private void NombreTextFieldKeyReleased(java.awt.event.KeyEvent evt) {
        BuscarAlumnos();
    }

		/**
		 * Metodo consultor, activado cuando se introduce caracteres en el campo "Primer apellido", para buscar alumnos por el primer apellido.
		 * @param evt (java.awt.event.KeyEvent) con el evento.
		 */

    private void PrimerApellidoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {
        BuscarAlumnos();
    }

		/**
		 * Metodo consultor, activado cuando se introduce caracteres en el campo "Segundo apellido", para buscar alumnos por el segundo apellido.
		 * @param evt (java.awt.event.KeyEvent) con el evento.
		 */

    private void SegundoApellidoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {
        BuscarAlumnos();
    }

		/**
		 * Metodo constructor, activado cada vez que seleccionas un jugador, actualiza el contador de alumnos seleccionados.
		 * @param evt (java.awt.event.MouseEvent) con el evento.
		 */

    private void ListaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {                                          

        AlumnosSelecionados.setText(Integer.toString(ListaAlumnos.getSelectedIndices().length));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList AlumnosMostrados;
    private javax.swing.JLabel AlumnosMostradosLabel;
    private javax.swing.JLabel AlumnosSelecionados;
    private javax.swing.JButton Añadir;
    private javax.swing.JLabel Buscar;
    private javax.swing.JButton Guardar;
    private javax.swing.JList ListaAlumnos;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JLabel PrimerApellido;
    private javax.swing.JTextField PrimerApellidoTextField;
    private javax.swing.JButton Quitar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel SegundoApellido;
    private javax.swing.JTextField SegundoApellidoTextField;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

		/**
		 * Metodo constructor que actualiza la lista de alumnos seleccionados cuando se añade o se quita un alumno.
		 */

    private void ActualizarJlist() {

        DefaultListModel modelo = new DefaultListModel();
        DefaultListModel modeloFinal = new DefaultListModel();
        List<Integer> ListaIDAlumnosMostrados = new ArrayList<Integer>();
        List<String> ListaAlumnosMostrados = new ArrayList<String>();
        String idAlum = "";
        String consulta = "";
        ResultSet retset;

        modelo = (DefaultListModel) AlumnosMostrados.getModel();
        ListaAlumnos.setModel(modeloFinal);

        for (int i = 0; i < modelo.size(); i++) {
            ListaAlumnosMostrados.add((String) modelo.get(i));
        }
        try {
            ListaIDAlumnosMostrados = GestorAlumnos.getIdAl(accesoBD, ListaAlumnosMostrados);
        } catch (SQLException ex) {
            Logger.getLogger(AñadirAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < ListaIDAlumnosMostrados.size(); i++) {
            idAlum = idAlum + Integer.toString(ListaIDAlumnosMostrados.get(i)) + ", ";
        }

        idAlum = idAlum.substring(0, idAlum.length() - 2);

        consulta = "SELECT primerApellido, segundoApellido, nombre FROM alumno WHERE "
                + "idAlumno NOT IN (" + idAlum + ")";

        System.out.println("La consulta es: " + consulta);

        retset = accesoBD.ejecutaConsulta(consulta);
        try {
            while (retset.next()) {
                modeloFinal.addElement(retset.getString(1) + " " + retset.getString(2) + " " + retset.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AñadirAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }

        ListaAlumnos.setModel(modeloFinal);
        AlumnosMostradosLabel.setText(Integer.toString(modelo.size()));

    }

		/**
		 * Metodo consultor, que consulta alumnos disponibles.
		 */

    private void BuscarAlumnos() {

        String nombre = NombreTextField.getText();
        DefaultListModel modelo = new DefaultListModel();
        String consulta = "SELECT primerApellido, segundoApellido, nombre FROM alumno WHERE idAlumno NOT IN (SELECT Alumno_idAlumno FROM pagoactividades WHERE Actividades_idActividades"
                + " =" + idActividad + ") AND ";
        String likeNombre = "";
        String likePApellido = "";
        String likeSApellido = "";

        if (!NombreTextField.getText().isEmpty() || !PrimerApellidoTextField.getText().isEmpty()
                || !SegundoApellidoTextField.getText().isEmpty()) {
            if (!NombreTextField.getText().isEmpty()) {
                likeNombre = "nombre LIKE '%";
                likeNombre = likeNombre + NombreTextField.getText() + "%' AND ";
            }

            if (!PrimerApellidoTextField.getText().isEmpty()) {
                likePApellido = "primerApellido LIKE '%";
                likePApellido = likePApellido + PrimerApellidoTextField.getText() + "%' AND ";
            }

            if (!SegundoApellidoTextField.getText().isEmpty()) {
                likeSApellido = "segundoApellido LIKE '%";
                likeSApellido = likeSApellido + SegundoApellidoTextField.getText() + "%' AND ";
            }

            if (!likeNombre.isEmpty()) {
                consulta = consulta + likeNombre;
            }

            if (!likePApellido.isEmpty()) {
                consulta = consulta + likePApellido;
            }

            if (!likeSApellido.isEmpty()) {
                consulta = consulta + likeSApellido;
            }

            consulta = consulta.substring(0, consulta.length() - 5);



            ResultSet retset = accesoBD.ejecutaConsulta(consulta);

            List<String> nuevosAlumnos = new ArrayList<String>();
            try {
                while (retset.next()) {
                    modelo.addElement(retset.getString(1) + " " + retset.getString(2) + " " + retset.getString(3));
                }
            } catch (SQLException ex) {
                Logger.getLogger(AñadirAlumno.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.print("\nModelo \n" + modelo);
            ListaAlumnos.setModel(modelo);
        } else {
            MostrarAlumnos();
        }
    }
}
