package InterfazUsuario;

import GestionDeCategorias.Categoria;
import GestionDeCategorias.GestorCategorias;
import ServiciosAlmacenamiento.BaseDatos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 ******************************************************************************
                   (c) Copyright 2013 
                   * 
                   * Moisés Gautier Gómez
                   * Julio Ros Martínez
                   * Francisco Javier Gómez del Olmo
                   * Francisco Santolalla Quiñonero
                   * Carlos Jesús Fernández Basso
                   * Alexander Moreno Borrego
                   * Jesús Manuel Contreras Siles
                   * Diego Muñoz Rio
 
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************
 */


/**
 * Clase encargada de proporcionar la interfaz para gestionar todo lo 
 * referente a las Categorias.
 * @author Diego
 */
public class AñadirModificarCategoria extends javax.swing.JFrame {
    private PrincipalCategorias pP;
    private BaseDatos bd;
    private String tAnt, dAnt;
    private int eAnt;
    private int EdadMinima;
    
    /**
     * Crea una nueva ventana para añadir una categoria.
     */
    public AñadirModificarCategoria(PrincipalCategorias pP, BaseDatos bd) {
        initComponents();
        setLocationRelativeTo(pP);
        this.pP = pP;
        this.bd = bd;
        this.jLabel4.setVisible(false);
        this.botonGuardar.setVisible(false);
        setTitle("Añadir categoría");
    }
    
    /**
     * Crea una nueva ventana para modificar una categoria.
     */
    public AñadirModificarCategoria(PrincipalCategorias pP, BaseDatos bd, String t, String d, int e) {
        initComponents();
        this.setLocationRelativeTo(pP);
        this.bd = bd;
        this.pP = pP;
        this.textTipo.setText(t);
        this.textDesc.setText(d);
        this.fieldEdadMinima.setText(String.valueOf(e));
        this.tAnt = t;
        this.dAnt = d;
        this.eAnt = e;
        this.jLabel1.setVisible(false);
        this.botoAceptar.setVisible(false);
        setTitle("Modificar categoría");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textDesc = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        botoAceptar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        labelEdadMinima = new javax.swing.JLabel();
        fieldEdadMinima = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nueva Categoria");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Modificar Categoria");

        jLabel2.setText("Tipo:");

        textTipo.setMinimumSize(new java.awt.Dimension(100, 20));
        textTipo.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel3.setText("Descripcion:");

        textDesc.setMinimumSize(new java.awt.Dimension(100, 20));
        textDesc.setPreferredSize(new java.awt.Dimension(100, 20));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botoAceptar.setText("Aceptar");
        botoAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAceptarActionPerformed(evt);
            }
        });

        botonGuardar.setText("Aceptar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        labelEdadMinima.setText("Edad Mínima:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botoAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEdadMinima)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(fieldEdadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(105, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(104, 104, 104)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(167, Short.MAX_VALUE)
                    .addComponent(botonGuardar)
                    .addGap(90, 90, 90)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdadMinima)
                    .addComponent(fieldEdadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botoAceptar))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 117, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(119, Short.MAX_VALUE)
                    .addComponent(botonGuardar)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Permite añadir una nueva caegoria en la base de datos. Si falta algun dato,
     * lo notifica mediante un mensaje de error.
     * @param evt Generado por la accion de un componente de la interfaz, proporciona 
     * algunas caracteristicas del evento.
     */
    private void botoAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAceptarActionPerformed
        if(!textTipo.getText().isEmpty() && !textDesc.getText().isEmpty() && !fieldEdadMinima.getText().isEmpty()){
            try {
                if(fieldEdadMinima.getText().matches("[0-9]{1,45}"))
                    EdadMinima = Integer.parseInt(fieldEdadMinima.getText());
                else
                    JOptionPane.showMessageDialog(this, "Debe modificar algun campo", "Error", JOptionPane.ERROR_MESSAGE);
                
                GestorCategorias.InsertarDatosCategorias(this.bd, textTipo.getText(), textDesc.getText(), Integer.parseInt(fieldEdadMinima.getText()));
                pP.actualizarTabla();
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(AñadirModificarCategoria.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else
            JOptionPane.showMessageDialog(this, "Debe rellenar los campos", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botoAceptarActionPerformed

    /**
     * Cierra la ventana de manipulacion de categorias sin realizar ningun cambio.
     * @param evt Generado por la accion de un componente de la interfaz, proporciona 
     * algunas caracteristicas del evento.
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * Permite modificar una categoria insertando los datos que se desean modificar. 
     * Si falta algun dato por insertar, lo notifica mediante un mensaje de error.
     * @param evt Generado por la accion de un componente de la interfaz, proporciona 
     * algunas caracteristicas del evento.
     */
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if(!textTipo.getText().isEmpty() && !textDesc.getText().isEmpty() && !fieldEdadMinima.getText().isEmpty()){
            
            if(fieldEdadMinima.getText().matches("[0-9]{1,2}"))
                EdadMinima = Integer.parseInt(fieldEdadMinima.getText());
            else
                JOptionPane.showMessageDialog(this, "Debe modificar algun campo", "Error", JOptionPane.ERROR_MESSAGE);
            
            if(!tAnt.equals(textTipo.getText()) || !dAnt.equals(textDesc.getText()) || !(eAnt == EdadMinima)) {
                Categoria cNuevo = new Categoria(textTipo.getText(), textDesc.getText(), Integer.parseInt(fieldEdadMinima.getText()));
                Categoria cViejo = new Categoria(tAnt, dAnt, eAnt);
                
                try {
                    GestorCategorias.ModificarCategoria(this.bd, cNuevo, cViejo,EdadMinima);
                    pP.actualizarTabla();
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(AñadirModificarCategoria.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe modificar algun campo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else
            JOptionPane.showMessageDialog(this, "Debe rellenar los campos", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botonGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField fieldEdadMinima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelEdadMinima;
    private javax.swing.JTextField textDesc;
    private javax.swing.JTextField textTipo;
    // End of variables declaration//GEN-END:variables

    
}
