/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

/**
 * Clase JugarPartido que sirve para visualizar la introducción de las 
 * estadísticas de los jugadores en los partidos.
 * @author Julio
 * @version 1.0
 */
public class JugarPartido extends javax.swing.JFrame {

    /**
     * Creates new form JugarPartido
     */
    public JugarPartido() {
        initComponents();
        this.setSize(600, 400);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jugador4 = new javax.swing.JComboBox();
        Jugador5 = new javax.swing.JComboBox();
        Jugador1 = new javax.swing.JComboBox();
        Jugador2 = new javax.swing.JComboBox();
        Jugador3 = new javax.swing.JComboBox();
        MedioCampo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaAlumnosEquipos = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Jugador4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Jugador4);
        Jugador4.setBounds(380, 250, 56, 20);

        Jugador5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Jugador5);
        Jugador5.setBounds(380, 390, 56, 20);

        Jugador1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Jugador1);
        Jugador1.setBounds(530, 320, 56, 20);

        Jugador2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Jugador2);
        Jugador2.setBounds(460, 220, 56, 20);

        Jugador3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Jugador3);
        Jugador3.setBounds(460, 420, 56, 20);

        MedioCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/medio_campo.jpg"))); // NOI18N
        getContentPane().add(MedioCampo);
        MedioCampo.setBounds(360, 180, 266, 300);

        ListaAlumnosEquipos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaAlumnosEquipos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 190, 180, 280);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/play.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 100, 60, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/pause.jpg"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 100, 60, 40);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Jugador", "Puntos", "% Tiros Campo", "% Tiros libres", "% Triples", "Rebotes Ofensivos", "Rebotes Defensivos", "Asistencias", "Robos", "Perdidas", "Tapones realizados", "Tapones recibidos", "Valoración"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleParent(ListaAlumnosEquipos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 490, 1040, 120);

        jLabel3.setText("LOCAL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 50, 60, 20);

        jLabel4.setText("VISITANTE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(880, 50, 110, 20);

        jScrollPane3.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(170, 80, 50, 22);

        jScrollPane4.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(880, 80, 50, 22);

        jLabel5.setText("TIEMPO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 40, 70, 20);

        jScrollPane5.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(560, 70, 80, 22);

        jLabel6.setText("SUPLENTES");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 160, 70, 20);

        jButton3.setText("+1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(700, 190, 47, 23);

        jButton4.setText("+0");
        getContentPane().add(jButton4);
        jButton4.setBounds(780, 190, 47, 23);

        jButton5.setText("+2");
        getContentPane().add(jButton5);
        jButton5.setBounds(700, 240, 47, 23);

        jButton6.setText("+0");
        getContentPane().add(jButton6);
        jButton6.setBounds(780, 240, 47, 23);

        jButton7.setText("+3");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(700, 290, 47, 23);

        jLabel1.setText("Tiros Libres");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(700, 160, 100, 20);

        jLabel7.setText("Tiros de Campo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(700, 220, 90, 20);

        jLabel8.setText("Triple");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(700, 270, 26, 14);

        jButton8.setText("+0");
        getContentPane().add(jButton8);
        jButton8.setBounds(780, 290, 47, 23);

        jLabel9.setText("Rebotes");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(700, 320, 110, 20);

        jButton9.setText("Of.");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(700, 340, 49, 23);

        jButton11.setText("Def.");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(780, 340, 53, 23);

        jLabel10.setText("Asistencias");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(880, 270, 70, 20);

        jLabel11.setText("Robos/Pérdidas");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(880, 160, 110, 20);

        jLabel13.setText("Tapones");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(880, 220, 41, 14);

        jButton10.setText("+1");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(880, 290, 47, 23);

        jButton12.setText("Robo");
        getContentPane().add(jButton12);
        jButton12.setBounds(880, 190, 57, 23);

        jButton13.setText("Pérdida");
        getContentPane().add(jButton13);
        jButton13.setBounds(970, 190, 69, 23);

        jButton14.setText("Realizado");
        getContentPane().add(jButton14);
        jButton14.setBounds(880, 240, 79, 23);

        jButton15.setText("Recibido");
        getContentPane().add(jButton15);
        jButton15.setBounds(970, 240, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JugarPartido().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Jugador1;
    private javax.swing.JComboBox Jugador2;
    private javax.swing.JComboBox Jugador3;
    private javax.swing.JComboBox Jugador4;
    private javax.swing.JComboBox Jugador5;
    private javax.swing.JList ListaAlumnosEquipos;
    private javax.swing.JLabel MedioCampo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
