/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

import GestionDeEquipos.Equipo;
import GestionDeEquipos.GestorEquipos;
import ServiciosAlmacenamiento.BaseDatos;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.border.Border;

/**
 *
 * @author 
 */

/*
 ******************************************************************************
                   (c) Copyright 2013 
                   * 
                   * Moisés Gautier Gómez
                   * Julio Ros Martínez
                   * Francisco Javier Gómez del Olmo
                   * Francisco Santolalla Quiñonero
                   * Carlos Jesús Fernández Basso
                   * Alexander Moreno Borrego
                   * Jesús Manuel Contreras Siles
                   * Diego Muñoz Rio
 
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************
 */

public class ModificarEquipo extends javax.swing.JFrame {

    /* Declaracion de variables */
    
    BaseDatos accesoBD;
    DefaultListModel modeloGuardar = new DefaultListModel(); 
    Border bordeError;
    String nombreEquipo, campoCategoria, campoTemporada, campoPrimerEntr, campoSegundoEntr, campoSexo;
    String nombreEquipo_anterior, campoPrimerEntr_anterior;
    
    /**
     * Constructor predeterminado de la clase
     */
    public ModificarEquipo() {
        initComponents();
    }
    
    /**
     * Constructor de la clase
     * @param acceso
     * @param nombreEquip
     * @param selecCat
     * @param selecTemp
     * @param primerEntr
     * @param segundoEntr
     * @param sexo
     * @throws SQLException 
     */
    public ModificarEquipo(BaseDatos acceso, String nombreEquip, String selecCat, String selecTemp, String primerEntr, String segundoEntr, String sexo) throws SQLException
    {
        initComponents();
        this.setLocation(300, 300);
        accesoBD = acceso;
        bordeError = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        this.actualizarCategoria();
        this.actualizarTemporada();
        this.actualizarSexo();
        nombreEquipo_anterior = nombreEquip;
        campoPrimerEntr_anterior = primerEntr;
        this.fieldNombreEquipo.setText(nombreEquip);
        this.comboCat.setSelectedItem(selecCat);
        this.comboTemp.setSelectedItem(selecTemp);
        this.actualizarEntrenadores();
        this.comboPrimerEntrenador.setSelectedItem(primerEntr);
        this.comboSegundoEntrenador.setSelectedItem(segundoEntr);
        this.comboSexo.setSelectedItem(sexo);
        
    }
    
    private void actualizarEntrenadores() throws SQLException
    {
        comboPrimerEntrenador.removeAllItems();
        comboSegundoEntrenador.removeAllItems();
        String consulta = "SELECT CONCAT(`nombre`,' ',`primerApellido`,' ',`segundoApellido`) as nombre FROM Usuario " 
                + "WHERE entrenador = 1";
        ResultSet retset = accesoBD.ejecutaConsulta(consulta);


        while (retset.next()) {
            comboPrimerEntrenador.addItem(retset.getString(1));
            comboSegundoEntrenador.addItem(retset.getString(1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelModificarEquipo = new javax.swing.JLabel();
        labelNombreEquipo = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        labelTemporada = new javax.swing.JLabel();
        labelPrimerEntrenador = new javax.swing.JLabel();
        laberSegundoEntrenador = new javax.swing.JLabel();
        comboCat = new javax.swing.JComboBox();
        comboTemp = new javax.swing.JComboBox();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        fieldNombreEquipo = new javax.swing.JTextField();
        comboPrimerEntrenador = new javax.swing.JComboBox();
        comboSegundoEntrenador = new javax.swing.JComboBox();
        labelSexo = new javax.swing.JLabel();
        comboSexo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("ModificarEquipo"); // NOI18N

        labelModificarEquipo.setText("Modificar equipo:");

        labelNombreEquipo.setText("Nombre:");

        labelCategoria.setText("Categoria:");

        labelTemporada.setText("Temporada:");

        labelPrimerEntrenador.setText("Primer Entrenador:");

        laberSegundoEntrenador.setText("Segundo Entrenador:");

        comboCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboTemp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        comboPrimerEntrenador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboSegundoEntrenador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelSexo.setText("Sexo:");

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelModificarEquipo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombreEquipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCategoria)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(botonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(labelTemporada)
                                .addGap(18, 18, 18)
                                .addComponent(comboTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(labelPrimerEntrenador)
                                .addGap(18, 18, 18)
                                .addComponent(comboPrimerEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(laberSegundoEntrenador)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonGuardar)
                                    .addComponent(comboSegundoEntrenador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(37, 37, 37)
                        .addComponent(labelSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelModificarEquipo)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreEquipo)
                    .addComponent(labelCategoria)
                    .addComponent(labelTemporada)
                    .addComponent(comboCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrimerEntrenador)
                    .addComponent(comboPrimerEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSexo)
                    .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laberSegundoEntrenador)
                    .addComponent(comboSegundoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonGuardar))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento 
     * @param evt Parametro formal que representa el evento de pulsar
     * el boton de cancelacion de la operacion en el formulario.
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * Evento
     * @param evt Parametro formal que representa el evento de pulsar
     * el boton de guardar los contenidos introducidos en el formulario.
     */
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        
        nombreEquipo = this.fieldNombreEquipo.getText();
        campoCategoria = this.comboCat.getSelectedItem().toString();
        campoPrimerEntr = this.comboPrimerEntrenador.getSelectedItem().toString();
        campoSegundoEntr = this.comboSegundoEntrenador.getSelectedItem().toString();
        campoTemporada = this.comboTemp.getSelectedItem().toString();
        campoSexo = this.comboSexo.getSelectedItem().toString();
        
        String fundacion = "SELECT Equipo.idEquipo, rango.Equipo_Fundacion_idFundacion FROM rango, equipo, usuario WHERE equipo.idEquipo = rango.Equipo_idEquipo AND "
                + "equipo.nombre = '"+ nombreEquipo_anterior +"' AND usuario.idUsuario = rango.Usuario_idUsuario AND CONCAT(`usuario`.`nombre`,' ',`usuario`.`primerApellido`,' ',`usuario`.`segundoApellido`) = '"+ campoPrimerEntr_anterior +
                "' AND rango.tipo = 'Primero'"; 
        int int_fundacion = 0;
        try {
        ResultSet res = accesoBD.ejecutaConsulta(fundacion);
            
            if(res.next())
            {
                int_fundacion = res.getInt(1);
            }
                
            
        } catch (SQLException ex) {
            Logger.getLogger(ModificarEquipo.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        boolean valor = (int_fundacion == 1)? true : false;
        
        
        Equipo equipo = new Equipo(nombreEquipo, campoTemporada, campoCategoria, campoPrimerEntr, campoSegundoEntr, valor, campoSexo);
        
        try {
            GestorEquipos.modificarEquipos(accesoBD, equipo);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarEquipo.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        this.setVisible(false);
        this.setEnabled(false);
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void actualizarCategoria() throws SQLException {
        comboCat.removeAllItems();
        String consulta = "SELECT tipo FROM categoria";
        ResultSet retset = accesoBD.ejecutaConsulta(consulta);


        while (retset.next()) {
            comboCat.addItem(retset.getString(1));
        }
    }
    
    private void actualizarSexo() throws SQLException
    {
        comboSexo.removeAllItems();
        
        comboSexo.addItem('V');
        comboSexo.addItem('H');
        
    }
    
    private void actualizarTemporada() throws SQLException {
        comboTemp.removeAllItems();
        String consulta = "SELECT curso FROM temporada";
        ResultSet retset = accesoBD.ejecutaConsulta(consulta);

        while (retset.next()) {
            comboTemp.addItem(retset.getString(1));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarEquipo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JComboBox comboCat;
    private javax.swing.JComboBox comboPrimerEntrenador;
    private javax.swing.JComboBox comboSegundoEntrenador;
    private javax.swing.JComboBox comboSexo;
    private javax.swing.JComboBox comboTemp;
    private javax.swing.JTextField fieldNombreEquipo;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelModificarEquipo;
    private javax.swing.JLabel labelNombreEquipo;
    private javax.swing.JLabel labelPrimerEntrenador;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTemporada;
    private javax.swing.JLabel laberSegundoEntrenador;
    // End of variables declaration//GEN-END:variables
}
