/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

import GestionDeAlumnos.GestorAlumnos;
import GestionDeCategorias.GestorCategorias;
import GestionDeGrupos.GestorGrupos;
import GestionDeGrupos.Grupo;
import GestionDeInstalaciones.GestorInstalacion;
import GestionDeTemporadas.GestorTemporadas;
import GestionDeUsuarios.GestorUsuarios;
import ServiciosAlmacenamiento.BaseDatos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class PrincipalGrupos extends javax.swing.JFrame {
    private BaseDatos bd;
    
    /**
     * Creates new form PrincipalGrupos
     */
    public PrincipalGrupos(JFrame pP, BaseDatos bd) {
        initComponents();
        this.bd = bd;
        setLocationRelativeTo(pP);

        try {
            /* Rellenar lista de temporadas */
            List<String> temps = GestorTemporadas.getListaTemporadas(this.bd);
            actualizaComboTempEnt(temps);

            /* Rellenar lista de categorias */
            actualizaComboCatGrup();
        } catch (SQLException ex) {
            Logger.getLogger(AñadirModificarTemporada.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Rellenar lista de entrenadores */
        List<String> ents = getListaEntrenadores("");
        comboEntGrup.removeAllItems();
        comboEntGrup.addItem("-Ninguno-");
        actualizaComboEntGrup(ents);

        /* Rellenar tabla de grupos */
        try {
            actualizaTablaGrupos();
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboTempEntr = new javax.swing.JComboBox();
        comboCatGrup = new javax.swing.JComboBox();
        comboEntGrup = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        tfGrupEnt = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGrupos = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        botonConsGrupo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        botonNuevoGrupEnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Grupos de Entrenamiento");
        jPanel1.add(jLabel4);

        getContentPane().add(jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel9.setPreferredSize(new java.awt.Dimension(400, 40));

        jLabel2.setText("Buscar:");

        comboEntGrup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Entrenador-" }));
        comboEntGrup.setMaximumSize(new java.awt.Dimension(174, 20));
        comboEntGrup.setMinimumSize(new java.awt.Dimension(174, 20));
        comboEntGrup.setPreferredSize(new java.awt.Dimension(174, 20));

        jLabel7.setText("Filtrar entrenador:");

        tfGrupEnt.setText("Buscar...");
        tfGrupEnt.setMaximumSize(new java.awt.Dimension(70, 20));
        tfGrupEnt.setMinimumSize(new java.awt.Dimension(70, 20));
        tfGrupEnt.setPreferredSize(new java.awt.Dimension(70, 20));
        tfGrupEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfGrupEntMouseClicked(evt);
            }
        });
        tfGrupEnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfGrupEntKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTempEntr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCatGrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfGrupEnt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEntGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboTempEntr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEntGrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfGrupEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCatGrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(508, 40));

        jButton1.setText("Filtrar Grupos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1);

        jButton2.setText("Mostrar todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton2);

        jPanel4.add(jPanel10);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 10, 10));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(jSeparator2);

        jPanel4.add(jPanel2);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        tablaGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaGrupos);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel11.add(jPanel12);

        botonConsGrupo.setText("Consultar");
        botonConsGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsGrupoActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        botonNuevoGrupEnt.setText("Nuevo");
        botonNuevoGrupEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoGrupEntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonNuevoGrupEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsGrupo)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonNuevoGrupEnt)
                .addGap(9, 9, 9)
                .addComponent(botonConsGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel13);

        jPanel4.add(jPanel11);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsGrupoActionPerformed
        int filaSel = tablaGrupos.getSelectedRow();
        if (filaSel == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un grupo", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String idGrupo = (String) tablaGrupos.getValueAt(filaSel, 0);

            try {
                new ConsultarGrupo(this, idGrupo).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonConsGrupoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int filaSel = tablaGrupos.getSelectedRow();
        if (filaSel == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un grupo", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int continuar = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el grupo?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (continuar == JOptionPane.YES_OPTION) {
                int idCat = 0, idEnt = 0, idInst = 0, idTemp = 0;
                String temp = "";

                int idGrup = Integer.parseInt((String) tablaGrupos.getValueAt(filaSel, 0));
                String cat = (String) tablaGrupos.getValueAt(filaSel, 2);
                String ent = (String) tablaGrupos.getValueAt(filaSel, 3);
                String inst = (String) tablaGrupos.getValueAt(filaSel, 4);

                try {
                    idCat = GestorCategorias.getIdCategoria(this.bd, cat);
                    idEnt = GestorUsuarios.getIdEnt(this.bd, ent);
                    idInst = GestorInstalacion.getIdInstalacion(this.bd, inst);
                    idTemp = GestorGrupos.getIdTemporada(this.bd, idGrup);
                    temp = GestorTemporadas.getTemporada(this.bd, idTemp);
                } catch (SQLException ex) {
                    Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

                Grupo g = new Grupo(cat, ent, inst, temp);
                g.setIdGrupo(idGrup);
                g.setIdCat(idCat);
                g.setIdEnt(idEnt);
                g.setIdInst(idInst);
                g.setIdTemp(idTemp);

                boolean GrupoEliminado = false;

                try {
                    GrupoEliminado = GestorGrupos.EliminarGrupos(this.bd, g);
                } catch (SQLException ex) {
                    Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (GrupoEliminado) {
                    JOptionPane.showMessageDialog(this, "Grupo Eliminado con exito", "Exito", JOptionPane.NO_OPTION);

                    try {
                        actualizaTablaGrupos();
                    } catch (SQLException ex) {
                        Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se ha podido borrar el grupo", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void botonNuevoGrupEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoGrupEntActionPerformed
        try {
            /*try {
                new NuevoGrupo(this).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            new NuevoGrupo(this, this.bd).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonNuevoGrupEntActionPerformed

    private void tfGrupEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfGrupEntMouseClicked
        tfGrupEnt.setText("");
        tfGrupEnt.requestFocus();
    }//GEN-LAST:event_tfGrupEntMouseClicked

    private void tfGrupEntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGrupEntKeyTyped
        String sEnt = tfGrupEnt.getText();
        List<String> ents = getListaEntrenadores(sEnt);
        comboEntGrup.removeAllItems();
        actualizaComboEntGrup(ents);
    }//GEN-LAST:event_tfGrupEntKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            actualizaTablaGruposFiltro(comboTempEntr.getSelectedItem().toString(),
                comboCatGrup.getSelectedItem().toString(), comboEntGrup.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            actualizaTablaGrupos();
            comboCatGrup.setSelectedIndex(0);
            comboTempEntr.setSelectedIndex(0);
            comboEntGrup.setSelectedIndex(0);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void actualizaComboTempEnt(List<String> temps) {
        comboTempEntr.addItem("-Ninguno-");
        for (String s : temps) {
            comboTempEntr.addItem(s);
        }
    }
    
    private void actualizaComboEntGrup(List<String> ents) {
        for (String s : ents) {
            comboEntGrup.addItem(s);
        }
    }

    private void actualizaComboCatGrup() throws SQLException {
        comboCatGrup.removeAllItems();
        comboCatGrup.addItem("-Ninguno-");
        List<String> listaCats = GestorCategorias.getTipoCategorias(this.bd);

        for (String s : listaCats) {
            comboCatGrup.addItem(s);
        }
    }
    public List<String> getListaEntrenadores(String sEnt) {
        List<String> ents = new ArrayList<>();
        try {
            ents = GestorUsuarios.getEntrenadores(this.bd, sEnt);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        return ents;
    }
    
    public void actualizaTablaGrupos() throws SQLException {
        List<List<String>> grupos = GestorGrupos.getListaGrupos(this.bd);

        String aux;
        Object[][] data = new Object[grupos.size()][5];
        for (int i = 0; i < grupos.size(); i++) {
            aux = grupos.get(i).get(0);
            data[i][0] = aux.substring(0, aux.indexOf(","));
            aux = aux.substring(aux.indexOf(",") + 1, aux.length());
            data[i][1] = aux.substring(0, aux.indexOf(","));
            aux = aux.substring(aux.indexOf(",") + 1, aux.length());
            data[i][2] = getCategoria(aux.substring(0, aux.indexOf(",")));
            aux = aux.substring(aux.indexOf(",") + 1, aux.length());
            data[i][3] = getEntrenador(aux.substring(0, aux.indexOf(",")));
            aux = aux.substring(aux.indexOf(",") + 1, aux.length());
            data[i][4] = getTemporada(aux);
        }
        
        DefaultTableModel dtm = new DefaultTableModel(data, new String[] { "ID Grupo", "Numero Alumnos", "Categoria", "Entrenador", "Temporada"}) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class};
            boolean[] canEdit = new boolean[] { false, false, false, false, false };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };

        tablaGrupos.setModel(dtm);
        
    }
    private String getCategoria(String s) throws SQLException {
        return GestorCategorias.getCategoria(this.bd, Integer.parseInt(s));
    }

    private String getEntrenador(String s) throws SQLException {
        return GestorUsuarios.getEntrenador(this.bd, s);
    }

    private String getTemporada(String s) throws SQLException {
        return GestorTemporadas.getTemporada(this.bd, s);
    }

    List<String> getlistaAlumnosIntroducidos(String idGrupo) throws SQLException {
        return GestorGrupos.getListaAlumnosIntroducidos(this.bd, idGrupo);
    }

    List<String> getListaTemps() throws SQLException {
        return GestorTemporadas.getListaTemporadas(this.bd);
    }

    List<String> getListaAlumnosSinGrupo(String s) throws SQLException {
        return GestorAlumnos.getAlumnosSinGrupo(this.bd, s);
    }

    List<String> getListaInstalaciones(String s) throws SQLException {
        return GestorInstalacion.getListaInstalaciones(this.bd);
    }

    List<String> getListaAlumnos(String s) throws SQLException {
        return GestorAlumnos.getAlumnos(this.bd, s);
    }
    
    private void actualizaTablaGruposFiltro(String temporada, String categoria, String entrenador) throws SQLException {
        List<List<String>> grupos = GestorGrupos.getListaGruposFiltro(this.bd, temporada, categoria, entrenador);

        String aux;
        Object[][] data = new Object[grupos.size()][5];
        for (int i = 0; i < grupos.size(); i++) {
            aux = grupos.get(i).get(0);
            data[i][0] = aux.substring(0, aux.indexOf(","));
            aux = aux.substring(aux.indexOf(",") + 1, aux.length());
            data[i][1] = aux.substring(0, aux.indexOf(","));
            aux = aux.substring(aux.indexOf(",") + 1, aux.length());
            data[i][2] = getCategoria(aux.substring(0, aux.indexOf(",")));
            aux = aux.substring(aux.indexOf(",") + 1, aux.length());
            data[i][3] = getEntrenador(aux.substring(0, aux.indexOf(",")));
            aux = aux.substring(aux.indexOf(",") + 1, aux.length());
            data[i][4] = getTemporada(aux);
        }
        
        DefaultTableModel dtm = new DefaultTableModel(data, new String[] { "ID Grupo", "Numero Alumnos", "Categoria", "Entrenador", "Temporada"}) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class};
            boolean[] canEdit = new boolean[] { false, false, false, false, false };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };

        tablaGrupos.setModel(dtm);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsGrupo;
    private javax.swing.JButton botonNuevoGrupEnt;
    private javax.swing.JComboBox comboCatGrup;
    private javax.swing.JComboBox comboEntGrup;
    private javax.swing.JComboBox comboTempEntr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaGrupos;
    private javax.swing.JTextField tfGrupEnt;
    // End of variables declaration//GEN-END:variables
}
