/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

import GestionDeCategorias.Categoria;
import GestionDeCategorias.GestorCategorias;
import ServiciosAlmacenamiento.BaseDatos;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class PrincipalCategorias extends javax.swing.JFrame {
    private BaseDatos bd;
    /**
     * Creates new form GestionCategorias
     */
    public PrincipalCategorias(JFrame pP, BaseDatos bd) {
        initComponents();
        setLocationRelativeTo(pP);
        this.bd = bd;
        try {
            actualizarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalCategorias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        botonNuevaCat = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        botonModCat = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        botonElimCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestor de categorias");
        setMinimumSize(new java.awt.Dimension(350, 350));
        setPreferredSize(new java.awt.Dimension(350, 350));
        setResizable(false);

        jScrollPane7.setPreferredSize(new java.awt.Dimension(300, 200));

        tablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCategorias.setRowSelectionAllowed(true);
        jScrollPane7.setViewportView(tablaCategorias);

        jPanel1.add(jScrollPane7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Categorias");
        jPanel2.add(jLabel17);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 10, 10));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(jSeparator5);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 10, 5));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        botonNuevaCat.setText("Nueva");
        botonNuevaCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaCatActionPerformed(evt);
            }
        });
        jPanel6.add(botonNuevaCat);

        jPanel5.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 10, 5));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        botonModCat.setText("Modificar");
        botonModCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModCatActionPerformed(evt);
            }
        });
        jPanel7.add(botonModCat);

        jPanel5.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 10, 5));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        botonElimCat.setText("Eliminar");
        botonElimCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElimCatActionPerformed(evt);
            }
        });
        jPanel8.add(botonElimCat);

        jPanel5.add(jPanel8);

        jPanel3.add(jPanel5);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaCatActionPerformed
        new AñadirModificarCategoria(this, this.bd).setVisible(true);
    }//GEN-LAST:event_botonNuevaCatActionPerformed

    private void botonModCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModCatActionPerformed
        int fileSeleccionada = tablaCategorias.getSelectedRow();
        if (fileSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una categoría", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String tipoCat = (String) tablaCategorias.getValueAt(fileSeleccionada, 0);
            String descCat = (String) tablaCategorias.getValueAt(fileSeleccionada, 1);

            new AñadirModificarCategoria(this, this.bd, tipoCat, descCat).setVisible(true);
        }
    }//GEN-LAST:event_botonModCatActionPerformed

    private void botonElimCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElimCatActionPerformed
        int fileSeleccionada = tablaCategorias.getSelectedRow();
        if (fileSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una categoría", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String tipoCat = (String) tablaCategorias.getValueAt(fileSeleccionada, 0);
            String descCat = (String) tablaCategorias.getValueAt(fileSeleccionada, 1);

            Categoria c = new Categoria(tipoCat, descCat);
            int continuar = JOptionPane.showConfirmDialog(this, "¿Desea eliminar la categoria?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (continuar == JOptionPane.YES_OPTION) {
                GestorCategorias.EliminarCategorias(this.bd, c);
            }
            try {
                actualizarTabla();
            } catch (SQLException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonElimCatActionPerformed

    protected void actualizarTabla() throws SQLException {
        List<List<String>> listaCats = GestorCategorias.getListaCategorias(this.bd);
        String aux;
        Object[][] data = new Object[listaCats.size()][2];
        for (int i = 0; i < listaCats.size(); i++) {
            aux = listaCats.get(i).get(0);
            data[i][0] = aux.substring(0, aux.indexOf(" "));
            aux = aux.substring(aux.indexOf(" ") + 1, aux.length());
            data[i][1] = aux.substring(0, aux.length());
        }

        DefaultTableModel dtm = new DefaultTableModel(data, new String[] { "Tipo", "Descripcion"}) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.String.class};
            boolean[] canEdit = new boolean[] { false, false };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };

        tablaCategorias.setModel(dtm);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonElimCat;
    private javax.swing.JButton botonModCat;
    private javax.swing.JButton botonNuevaCat;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tablaCategorias;
    // End of variables declaration//GEN-END:variables
}
